name = 'odincova_dev'
autostart = true
# tracelevel is not used for now
tracelevel = 'DEBUG'

[SERIAL]
# Name of serial device in /dev
port = 'serial0'
baudrate = 115200
bytesize = 8
parity = 'N'
stopbits = 1
flowcontrol = 'off'

[NTRIPC]
# NTRIP Caster domain name or IP address string
domain = '192.168.100.16'
port = 2101
mountpoint = 'LENOVO1'
password = '123'
str = ''

[BASE]
autoconfig = true
# VALSET memory level = 'RAM', 'BBR', 'FLASH', 'ALL'
# Multiple levels example = ['RAM', 'BBR']
level = 'RAM'
# Time mode = 'Disabled' | 'SvIn' | 'Fixed'
mode = 'Fixed'
# Minimum observation time [s]
observe = 180
# Required positional accuracy [mm]
accuracy = 50_000
# Coordinates in WGS84 [m], decimal separator - dot
lat = 53.89878252
lon = 27.44895374
hgt = 303.882
