autostart = true
# tracelevel is not used for now
tracelevel = 'DEBUG'

[SERIAL]
port = 'serial0'
baudrate = 115200
bytesize = 8
parity = 'N'
stopbits = 1
flowcontrol = 'off'

[NTRIPC]
domain = 'odincova.ddns.net'
port = 2101
mountpoint = 'TST1'
username = 'SERGE'
password = '123'
str = ''
