name = 'odincova_dev'
tracelevel = 'DEBUG'
autostart = true
status_update_rate = 5

[POWER]
shutdown = 3.2
recovery = 4.2
timeout = 3

[SERIAL]
# Name of serial device in /dev
port = 'serial0'
baudrate = 115200
bytesize = 8
parity = 'N'
stopbits = 1
flowcontrol = 'off'

[NTRIPS]
inject = [1006, 1008, 1033]
anchor = 1005
interval = 1

[NTRIPC]
# NTRIP Caster domain name or IP address string
domain = 'RTK2go.com'
port = 2101
mountpoint = 'TST1'
password = 'shadow12'
str = ''

[BASE]
autoconfig = true
# Static basestation configuration file
configfile = '~/uBlox_config_base_devoffice_MSM4.txt'
# VALSET memory level = 'RAM', 'BBR', 'FLASH', 'ALL'
# Multiple levels example = ['RAM', 'BBR']
level = 'RAM'
# Time mode = 'Disabled' | 'SvIn' | 'Fixed'
mode = 'Fixed'
# Minimum observation time [s]
observe = 180
# Required positional accuracy [mm]
accuracy = 50_000
# Coordinates in WGS84 [m], decimal separator - dot
lat = 53.89878252
lon = 27.44895374
hgt = 303.882
