name = 'odincova_dev'
tracelevel = 'DEBUG'
autostart = true

[SERIAL]
# Name of serial device in /dev
port = 'serial0'
baudrate = 115200
bytesize = 8
parity = 'N'
stopbits = 1
flowcontrol = 'off'

[NTRIPS]
inject = [1008]
anchor = 1005
interval = 1

[NTRIPC]
# NTRIP Caster domain name or IP address string
domain = '192.168.100.19'
port = 5003
mountpoint = 'TST1'
password = '123'
str = ''

[BASE]
autoconfig = true
# VALSET memory level = 'RAM', 'BBR', 'FLASH', 'ALL'
# Multiple levels example = ['RAM', 'BBR']
level = 'RAM'
# Time mode = 'Disabled' | 'SvIn' | 'Fixed'
mode = 'Fixed'
# Minimum observation time [s]
observe = 180
# Required positional accuracy [mm]
accuracy = 50_000
# Coordinates in WGS84 [m], decimal separator - dot
lat = 53.89878252
lon = 27.44895374
hgt = 303.882
