autostart = true
# tracelevel is not used for now
tracelevel = 'DEBUG'
tmpfsdir = '/run/user/bs'

[SERIAL]
port = 'serial0'
baudrate = 115200
bytesize = 8
parity = 'N'
stopbits = 1
flowcontrol = 'off'

[NTRIPC]
domain = 'odincova.ddns.net'
port = 2101
mountpoint = 'TST1'
username = 'SERGE'
password = '123'
str = ''

[BASE]
# Time mode = 'Disabled' | 'SvIn' | 'Fixed'
mode = 'Fixed'
# Coordinates in WGS84, height in [m], decimal separator is dot
lat = 53.89878252
lon = 27.44895374
hgt = 303.882